baseurl: https://justinmklam.com
locale: en-us
title: justinmklam | blog

contentdir: content
layoutdir: layouts
publishdir: docs
canonifyurls: false
disableKinds:
  - section
  - taxonomy
enableEmoji: true

FootnoteReturnLinkContents: ↩

menu:
  main:
    - name: /home
      url: /
      weight: 1
    - name: /about
      url: /about
      weight: 2
    - name: /contact
      url: /contact
      weight: 3

taxonomies:
  tag: tags
  type: types

params:
  brand: justinmklam
  author: Justin Lam
  math: false
  icons: false
  pagerSize: 5
  featured:
    - /posts/2019/diy-wedding-ring/
    - /posts/2018/06/sourdough-starter-monitor
    - /posts/2017/06/sous-vide-pla
  highlightJs:
    version: 11.11.1
  umamiId: 6b7445a7-ca25-4dcd-b8b0-453ee282678e

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      # Mathjax. See https://gohugo.io/content-management/mathematics/
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true
  highlight:
    guessSyntax: true
    noClasses: false # Use external stylesheets instead so conditional light/dark highlighting can be used
    # style: github-dark # See https://gohugo.io/quick-reference/syntax-highlighting-styles/
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1

related:
  includeNewer: true
  indices:
  - applyFilter: false
    cardinalityThreshold: 0
    name: keywords
    pattern: ''
    toLower: false
    type: basic
    weight: 80
  - applyFilter: false
    cardinalityThreshold: 0
    name: date
    pattern: ''
    toLower: false
    type: basic
    weight: 10
  - applyFilter: false
    cardinalityThreshold: 0
    name: tags
    pattern: ''
    toLower: false
    type: basic
    weight: 100
  threshold: 80
  toLower: false
